name: Build GoldHEN Plugin

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # On utilise l'image Docker officielle d'OpenOrbis qui contient déjà TOUT (plus de 404 possible)
    container: openorbis/toolchain:v0.5.2

    steps:
    - name: Checkout du code du plugin
      uses: actions/checkout@v4

    - name: Compilation du Plugin PS4
      run: |
        # La variable OO_PS4_TOOLCHAIN est déjà configurée par défaut dans ce conteneur
        cd MyPluginPS4
        make clean && make

    - name: Téléversement du binaire (.prx)
      uses: actions/upload-artifact@v4
      with:
        name: GoldHEN-MyPluginPS4-Artifact
        path: "MyPluginPS4/*.prx"
